In [65]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [66]:
df1 = pd.read_csv(r'dataset/world-happiness-report-2021.csv')
df1.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [67]:
df1[df1['Country name'] == 'India']

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
138,India,South Asia,3.819,0.026,3.869,3.769,8.755,0.603,60.633,0.893,0.089,0.774,2.43,0.741,0.316,0.383,0.622,0.246,0.106,1.405

In [68]:
df = pd.read_csv(r'dataset/world-happiness-report.csv')

In [69]:
df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [70]:
df.shape

(1949, 11)

In [71]:
df[df['Country name'] == 'India']

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
732,India,2006,5.348,8.145,0.707,55.72,0.774,NaN,0.855,0.687,0.199
733,India,2007,5.027,8.204,0.569,56.14,0.729,-0.051,0.862,0.668,0.253
734,India,2008,5.146,8.220,0.684,56.56,0.756,-0.072,0.891,0.674,0.259
735,India,2009,4.522,8.281,0.653,56.98,0.679,-0.026,0.895,0.771,0.301
736,India,2010,4.989,8.349,0.605,57.40,0.783,0.058,0.863,0.697,0.267
737,India,2011,4.635,8.387,0.553,57.70,0.838,-0.038,0.908,0.648,0.232
738,India,2012,4.720,8.428,0.511,58.00,0.609,0.067,0.830,0.629,0.295
739,India,2013,4.428,8.478,0.553,58.30,0.740,0.084,0.832,0.680,0.330
740,India,2014,4.424,8.538,0.621,58.60,0.809,-0.026,0.832,0.711,0.285
741,India,2015,4.342,8.604,0.610,58.90,0.777,-0.005,0.776,0.701,0.322
742,India,2016,4.179,8.673,0.614,59.30,0.820,0.046,0.765,0.695,0.346
743,India,2017,4.046,8.730,0.607,59.70,0.886,-0.042,0.781,0.682,0.318
744,India,2018,3.818,8.779,0.638,60.10,0.890,0.085,0.805,0.657,0.357
745,India,2019,3.249,8.818,0.561,60.50,0.876,0.112,0.752,0.648,0.466
746,India,2020,4.225,8.703,0.617,60.90,0.906,0.075,0.780,0.752,0.383

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1949 entries, 0 to 1948
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country name                      1949 non-null   object
 1   year                              1949 non-null   int64
 2   Life Ladder                       1949 non-null   float64
 3   Log GDP per capita                1913 non-null   float64
 4   Social support                    1936 non-null   float64
 5   Healthy life expectancy at birth  1894 non-null   float64
 6   Freedom to make life choices      1917 non-null   float64
 7   Generosity                        1860 non-null   float64
 8   Perceptions of corruption         1839 non-null   float64
 9   Positive affect                   1927 non-null   float64
 10  Negative affect                   1933 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 167.6+ KB

In [73]:
df.isna().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [74]:
df['Log GDP per capita'].median()

np.float64(9.46)

In [75]:
df['Log GDP per capita'] = df['Log GDP per capita'].fillna(9.46)

In [76]:
df['Social support'].median()

np.float64(0.8354999999999999)

In [77]:
df['Social support'] = df['Social support'].fillna(0.8355)

In [78]:
df['Healthy life expectancy at birth'].median()

np.float64(65.2)

In [79]:
df['Healthy life expectancy at birth'] = df['Healthy life expectancy at birth'].fillna(65.2)

In [80]:
df['Freedom to make life choices'].median()

np.float64(0.763)

In [81]:
df['Freedom to make life choices'] = df['Freedom to make life choices'].fillna(0.763)

In [82]:
df['Generosity'] = df['Generosity'].fillna(df['Generosity'].median())

In [83]:
df['Perceptions of corruption'] = df["Perceptions of corruption"].fillna(df['Perceptions of corruption'].median())

In [84]:
df['Positive affect'] = df["Positive affect"].fillna(df['Positive affect'].median())

In [85]:
df['Negative affect'] = df['Negative affect'].fillna(df['Negative affect'].median())

In [86]:
df.isna().sum()

Country name                        0
year                                0
Life Ladder                         0
Log GDP per capita                  0
Social support                      0
Healthy life expectancy at birth    0
Freedom to make life choices        0
Generosity                          0
Perceptions of corruption           0
Positive affect                     0
Negative affect                     0
dtype: int64

In [87]:
df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [88]:
df[df['Country name'] == 'Finland']

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
551,Finland,2006,7.672,10.745,0.965,69.76,0.969,-0.005,0.132,0.722,0.172
552,Finland,2008,7.671,10.796,0.951,70.08,0.934,0.028,0.217,0.773,0.144
553,Finland,2010,7.393,10.734,0.935,70.40,0.916,0.091,0.413,0.832,0.202
554,Finland,2011,7.354,10.754,0.938,70.64,0.936,0.101,0.320,0.773,0.205
555,Finland,2012,7.420,10.735,0.928,70.88,0.921,-0.001,0.361,0.796,0.202
556,Finland,2013,7.445,10.722,0.941,71.12,0.919,0.040,0.306,0.769,0.195
557,Finland,2014,7.385,10.714,0.952,71.36,0.933,-0.001,0.265,0.784,0.199
558,Finland,2015,7.448,10.716,0.948,71.60,0.930,0.111,0.223,0.751,0.191
559,Finland,2016,7.660,10.740,0.954,71.70,0.948,-0.027,0.250,0.797,0.182
560,Finland,2017,7.788,10.768,0.964,71.80,0.962,-0.002,0.192,0.787,0.176
561,Finland,2018,7.858,10.783,0.962,71.90,0.938,-0.127,0.199,0.782,0.182
562,Finland,2019,7.780,10.792,0.937,72.00,0.948,-0.052,0.195,0.755,0.181
563,Finland,2020,7.889,10.750,0.962,72.10,0.962,-0.116,0.164,0.744,0.193

In [89]:
df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [90]:
df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [91]:
del df['Country name']

### Using different algorithms

In [92]:
x = df.drop('Life Ladder', axis=1)
x.head()

,year,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,2008,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,2009,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,2010,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,2011,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,2012,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [93]:
y = df['Life Ladder']

In [94]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.30, random_state=25)

In [95]:


mm_scaler = MinMaxScaler()
x_train_scaled = mm_scaler.fit_transform(x_train)
x_test_scaled = mm_scaler.fit_transform(x_test)

In [106]:

lr = LinearRegression()

In [107]:
lr.fit(x_train_scaled, y_train)

LinearRegression()

In [108]:
y_pred =lr.predict(x_test_scaled)

In [111]:
from sklearn.metrics import r2_score, mean_squared_error

In [110]:
print(r2_score(y_test, y_pred))

0.7409197906894627

In [114]:
mse =mean_squared_error(y_test, y_pred)
print(mse)

0.3018383863826247

In [116]:
rmse = np.sqrt(mse)
print(rmse)

0.5493982038400059

#### Random Forest

In [117]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()

In [118]:
rf.fit(x_train_scaled, y_train)

RandomForestRegressor()

In [119]:
y_pred2 = rf.predict(x_test_scaled)

In [120]:
print(r2_score(y_test, y_pred2))

0.8261302392969025

In [122]:
mse = mean_squared_error(y_test, y_pred2)
print(mse)

0.20256494369453001

In [124]:
rmse = np.sqrt(mse)
print(rmse)

0.45007215387594246

Support Vector Regressor

In [125]:
from sklearn.svm import SVR
svr = SVR()

In [126]:
svr.fit(x_train_scaled, y_train)

SVR()

In [128]:
y_pred3 = svr.predict(x_test_scaled)

In [129]:
print(r2_score(y_test, y_pred3))

0.7991447095970556

In [131]:
mse = mean_squared_error(y_test, y_pred3)
print(mse)

0.23400412139921967

In [133]:
rsme = np.sqrt(mse)
print(rsme)

0.4837397248513085